version: '3'

services:
  tb_mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tb
      MONGO_INITDB_ROOT_PASSWORD: tb_password
    volumes:
      - tb_mongodb_data:/data/db

  tb_cassandra1:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: tb_CLUSTER
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
      - tb_cassandra1_data:/var/lib/cassandra

  tb_cassandra2:
    image: cassandra:latest
    environment:
      CASSANDRA_CLUSTER_NAME: tb_CLUSTER
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_SEEDS: tb_cassandra1
    volumes:
      - tb_cassandra2_data:/var/lib/cassandra

  tb_cassandra3:
    image: cassandra:latest
    environment:
      CASSANDRA_CLUSTER_NAME: tb_CLUSTER
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_SEEDS: tb_cassandra1
    volumes:
      - tb_cassandra3_data:/var/lib/cassandra

volumes:
  tb_mongodb_data:
  tb_cassandra1_data:
  tb_cassandra2_data:
  tb_cassandra3_data: