version: '3'

services:

  tb_cassandra1:
    image: cassandra:4.1.3
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: tb_CLUSTER
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_SEEDS: "tb_cassandra1,tb_cassandra2"
    volumes:
      - tb_cassandra1_data:/var/lib/cassandra

  tb_cassandra2:
    image: cassandra:4.1.3
    environment:
      CASSANDRA_CLUSTER_NAME: tb_CLUSTER
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_SEEDS: "tb_cassandra1,tb_cassandra2"
    volumes:
      - tb_cassandra2_data:/var/lib/cassandra

  tb_cassandra3:
    image: cassandra:4.1.3
    environment:
      CASSANDRA_CLUSTER_NAME: tb_CLUSTER
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_SEEDS: "tb_cassandra1,tb_cassandra2"
    volumes:
      - tb_cassandra3_data:/var/lib/cassandra

volumes:
  tb_cassandra1_data:
  tb_cassandra2_data:
  tb_cassandra3_data: